# Build program executable

# EXECUTABLE defines the name of the executable that will be generated
# SOURCES should include all the .c files in your project (do not include .h)

analyzer: main.c BellmanFord.c Common.c Graph.c 
	gcc-5 main.c BellmanFord.c Common.c Graph.c -o analyzer -fopenmp




